import type { NextPage } from "next";
import Head from "next/head";
import DropsGrid from "../components/DropsGrid";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col h-full py-8 ">
      <Head>
        <title>FeltZine - Fjord</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center justify-center ">
        <h1 className="text-[#f3efef] text-shadowInit1 text-2xl  md:text-4xl lg:text-5xl">
          Fjord x Felt Zine
        </h1>
      </div>
      <div className="noise" />
      <DropsGrid />
    </div>
  );
};

export default Home;
